[TAIPY]

[DATA_NODE.historical_data]
storage_type = "csv"
scope = "GLOBAL:SCOPE"
default_path = "time_series.csv"

[DATA_NODE.month]
scope = "CYCLE:SCOPE"

[DATA_NODE.month_data]
scope = "CYCLE:SCOPE"

[TASK.filter_by_month]
function = "__main__.filter_by_month:function"
inputs = [ "historical_data:SECTION", "month:SECTION",]
outputs = [ "month_data:SECTION",]
skippable = "False:bool"

[SCENARIO.my_scenario]
tasks = [ "filter_by_month:SECTION",]
additional_data_nodes = []
frequency = "MONTHLY:FREQUENCY"

[SCENARIO.my_scenario.comparators]

[SCENARIO.my_scenario.sequences]
