version: 2


mkdocs:
  configuration: mkdocs.yml

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    nodejs: "18"
  jobs:
    pre_install:
      - python tools/fetch_source_files.py MKDOCS
      - pip install pipenv
      - pipenv install --dev
      - pipenv run pip freeze >requirements.txt
      - pipenv run python tools/setup_generation.py
      - npm install -g npm@9.4.0
python:
   install:
   - requirements: requirements.txt
