[TAIPY]
read_entity_retry = "3:int"

[DATA_NODE.input]
default_data = "21:int"

[DATA_NODE.intermediate]

[DATA_NODE.output]

[TASK.double]
function = "__main__.double:function"
inputs = [ "input:SECTION",]
outputs = [ "intermediate:SECTION",]
skippable = "False:bool"

[TASK.add]
function = "__main__.add:function"
inputs = [ "intermediate:SECTION",]
outputs = [ "output:SECTION",]
skippable = "False:bool"

[PIPELINE.multiply_scenario_pipeline]
tasks = [ "double:SECTION", "add:SECTION",]
name = "my_scenario"

[SCENARIO.multiply_scenario]
pipelines = [ "multiply_scenario_pipeline:SECTION",]
name = "my_scenario"

[SCENARIO.multiply_scenario.comparators]
output = [ "__main__.compare_function:function",]
