[TAIPY]
read_entity_retry = "3:int"

[DATA_NODE.historical_temperature]

[DATA_NODE.date_to_forecast]

[DATA_NODE.predictions]

[TASK.predict]
function = "__main__.predict:function"
inputs = [ "historical_temperature:SECTION", "date_to_forecast:SECTION",]
outputs = [ "predictions:SECTION",]
skippable = "False:bool"

[PIPELINE.my_scenario_pipeline]
tasks = [ "predict:SECTION",]

[SCENARIO.my_scenario]
pipelines = [ "my_scenario_pipeline:SECTION",]

[SCENARIO.my_scenario.comparators]
