[TAIPY]

[JOB]
mode = "standalone"
max_nb_of_workers = "2:int"

[DATA_NODE.input]
scope = "SCENARIO:SCOPE"
default_data = "21:int"

[DATA_NODE.intermediate]
scope = "SCENARIO:SCOPE"
default_data = "21:int"

[DATA_NODE.output]
scope = "SCENARIO:SCOPE"

[TASK.double]
inputs = [ "input:SECTION",]
function = "__mp_main__.double:function"
outputs = [ "intermediate:SECTION",]
skippable = "False:bool"

[TASK.add]
inputs = [ "intermediate:SECTION",]
function = "__mp_main__.add:function"
outputs = [ "output:SECTION",]
skippable = "False:bool"

[PIPELINE.my_pipeline]
tasks = [ "double:SECTION", "add:SECTION",]

[SCENARIO.my_scenario]
pipelines = [ "my_pipeline:SECTION",]

[SCENARIO.my_scenario.comparators]
