[TAIPY]

[DATA_NODE.input]
scope = "SCENARIO:SCOPE"
default_data = "21:int"

[DATA_NODE.output]
scope = "SCENARIO:SCOPE"

[TASK.double]
inputs = [ "input:SECTION",]
function = "__main__.double:function"
outputs = [ "output:SECTION",]
skippable = "False:bool"

[PIPELINE.my_pipeline]
tasks = [ "double:SECTION",]

[SCENARIO.my_scenario]
pipelines = [ "my_pipeline:SECTION",]

[SCENARIO.my_scenario.comparators]
