name: Documentation Generation

on:
  push:
    branches: [doc/#529-gui-improvements]

jobs:
  Deploy-Doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pipenv and dependencies
        run: |
          python -m pip install pipenv
          python -m pipenv install --dev
      - name: Fetch Taipy Core code
        run: |
          mkdir tmp
          cd tmp
          git clone -b develop https://github.com/Avaiga/taipy.git
          mv taipy/taipy ..
          rm -rf taipy
        env:
          GITHUB_TOKEN: ${{ secrets.TAIPY_REPOS_ACCESS }}
      - name: Fetch Taipy Gui code and elements doc
        run: |
          cd tmp
          git clone -b develop https://github.com/Avaiga/taipy-gui.git
          (cd taipy-gui;tar cf - taipy gui)|(cd ..;tar xf -)
          rm -rf taipy-gui
        env:
          GITHUB_TOKEN: ${{ secrets.TAIPY_REPOS_ACCESS }}
      - name: Clean up
        run: rm -rf taipy
      - name: Generate Visual Elements doc
        run: |
          pipenv run python tools/mkdocs/generate_viselements.py
      - name: Build doc and deploy
        run: |
          pipenv run mkdocs gh-deploy --force
